V2 dev
NYPL/sfr-search-api pull request #4
Opened 2019-03-05 19:20 UTC by mwbenowitz

This implements a set of `v2` endpoints that provide access to the new ElasticSearch index, which contains updated documents and which is updated with new data.

The `v2` endpoints also implement a more flexible structure that makes it easier to add new endpoints and to extend existing functionality. Each set of endpoints re-uses the same response and error handlers, implementing logic around each individual type of request that is received.

This also implements a basic test suite, including both unit and simple integration tests to ensure that the API is both functioning and able to return results from an ElasticSearch instance.

2019-03-05 22:24 UTC, gkallenberg requested changes
Looking good. Just some minor adjustments I think make sense. Feel free to disagree or point out where I'm faulty in my assessment.

2019-03-05 22:24 UTC, gkallenberg commented on lib/client.js
> +  var client = new Elastic.Client({
`const` here?

2019-03-05 22:24 UTC, gkallenberg commented on lib/client.js
> +    }, function (error) {
perhaps this should be placed in a `.catch` block after `.then`?

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +    var contentType = 'application/json'
`const` here

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +    var resp = _resp
`const` here

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/work.js
> +    var contentType = 'application/json'
`const` here

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/work.js
> +    let respLen = resp['hits']['hits'].length
Are the `let` params necessary since they don't appear to be reassigned within the same instance? -- same for `recordID`, `body` and `params` below. might be better to use `const` instead.

`statusCode` below should be a `let`.

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +      params['filters'].map((filter) => {
Need to test whether `filters` is actually an array before calling `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +      params['queries'].map((term) => {
Need to test whether `queries` is actually an array before calling `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +      params['sort'].map((sort) => {
Need to test whether `sort` is actually an array before calling `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/search.js
> +      params['aggregations'].map((agg) => {
Need to test whether `aggregations` is actually an array before calling `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v2/search.js
> +  if ('filters' in params) {
Test for array before using `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v2/search.js
> +  if ('sort' in params) {
Test for array before using `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v2/search.js
> +  if ('aggregations' in params) {
Test for array before using `map`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v2/v2.js
> +  let contentType = 'application/json'
use `const`

2019-03-05 22:24 UTC, gkallenberg commented on routes/v1/work.js
> +    let singleResp = resp['hits']['hits'][0]['_source']
Use `const` instead of `let`

2019-03-06 15:19 UTC, mwbenowitz commented
Thanks for the feedback, updated the endpoints to use const/let everywhere as it should be and linted the files to make sure that we aren't using `const` for anything that can get reassigned.

Also implemented `instanceof` checking before invoking `map` in both of the search endpoints to ensure that this executes safely.

2019-03-11 16:55 UTC, gkallenberg approved these changes
A minor adjustment to a `var` as well as changing .nvmrc and .travis.yml to point to the base Node version of 10.15.1; otherwise, good to go.

2019-03-11 16:55 UTC, gkallenberg commented on lib/client.js
> +      var hits = body.hits.hits
if hits doesn't get re-assigned, this can change to `const`.

2019-03-11 21:12 UTC, mwbenowitz commented
Merged in a final commit to updated node version to `10.15` and fix the lingering `var` issue that Greg identified

2019-03-12 20:03 UTC, merged